### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by KristofferC** [fredrikekre/pgd#8]
I guess you have a symmetric pos def system. In your solvers you can use:

``` jl
ΔΔu = cholfact(Symmetric(K, :U))\g
Δu -= ΔΔu
```

to use cholesky factorization which is faster.

With the new contmechtensors I wrote the relevant parts in psi_intf as:

``` jl
        σ = σ_dev_degradation*( 2 * mp.G * dev(ε) + mp.K * trace(ε) * one(ε))
        σ_dev =dev(σ)
        σ_e = sqrt(3/2) * sqrt(σ_dev ⊡ σ_dev)
        σe_plot[q_point] = σ_e
```

Im not sure why you converted to 3d etc but maybe there was a reason

**Comment by KristofferC** [comment]
Nice elements bruh 
![image](https://cloud.githubusercontent.com/assets/1282691/13984230/305bf8e4-f0f5-11e5-9be0-bc9cbb7daf8e.png)

**Comment by fredrikekre** [comment]
Kolon pe

**Comment by KristofferC** [comment]
I did a reader for Comsol's mesh files: https://gist.github.com/KristofferC/4a20066289f0447e3c52

I needed to make a non uniform mesh and Comsol has a pretty nice one.

![image](https://cloud.githubusercontent.com/assets/1282691/13992040/b59d2224-f11a-11e5-8254-29d42765f4e4.png)

In case you want to put more elements in the middle or something, it could be useful.

**Comment by KristofferC** [comment]
https://github.com/KristofferC/ContMechTensors.jl/pull/10

kommer nog inte göra någon större skillnad

**Comment by KristofferC** [comment]
``` jl
immutable LEmtrl # Linear elastic material
    E::Float64
    ν::Float64
    G::Float64
    K::Float64
    I_dev_sym::Matrix
    I::Vector
end
```

`I::Vector`, `I_dev_sym::Matrix` är inte bra för prestanda eftersom julia inte kan veta vilken sorts vektor / matris det är. Antingen säg `Vector{Float64}` eller parametrisera:

``` jl
immutable LEmtrl{T}
.
.
I_dev_sym::Matrix{T}
end
```

**Comment by fredrikekre** [comment]
Använder den inte ens längre, så kan ta bort den :) Voigt form är ju deprecated nu ju... :)
Tråkigt på :train: eller? Sitter själv på en :bus: :tada:

**Comment by KristofferC** [comment]
Hoppar inte på tåget förrän om tre kvart. Framme (i Uppsala) 23:20...

**Comment by fredrikekre** [comment]
Om det är i tid ja! ;)

Är det typ inte billigare att flyga? Arlanda ligger ju inte så långt från Uppsala?

**Comment by KristofferC** [comment]
Jo, när jag hade ungdomsrabatt (R.I.P < 26 år) så var det billigare. Kostar dock typ 170 med tåget från Arlanda till Storvreta (en bit utanför Uppsala)...

**Comment by fredrikekre** [comment]
Okej... Inga fördelar med att bli vuxen ju :p
Innebandyspelare då? :)

**Comment by KristofferC** [comment]
En gång i tiden ;)  Som alla här.

**Comment by fredrikekre** [comment]
Gött! Där slutar min kunskap om Storvreta :)

**Comment by KristofferC** [comment]
Då är du full-lärd.

**Comment by fredrikekre** [comment]
:+1:

**Comment by KristofferC** [comment]
Nu sitter vi fast :). Folk som varit och sprungit på spåret..

**Comment by fredrikekre** [comment]
Standard.
Tur att dom forskar så mycket på järnväg på instutionen, de kanske löser problemen inom ett par år ;)

**Comment by KristofferC** [comment]
Fortf här... Kul liv.

**Comment by fredrikekre** [comment]
Segt :/
Mitt ute i skogen eller?

**Comment by KristofferC** [comment]
Katrineholm. Tåget tömt. Var tvungen att lämna bagaget. Snuten ska söka igenom tåget.. Fast på något annat ställe. Rip in piece påsk.

**Comment by fredrikekre** [comment]
Wut?! :s Bad luck...

**Comment by KristofferC** [comment]
Kolla typ unt.se

**Comment by fredrikekre** [comment]
Nån som uttalat sig så någon blev orolig? Är väl bra att dom tar det på allvar kanske, men känns lite vagt ...
Hoppas du kommer fram på nåt vänster
Godnatt!

**Comment by KristofferC** [comment]
Jag märkte att skapa styvhetsmatrisen först och assemblera in i den är snabbare än att hela tiden skapa en ny styvhetsmatris med `begin_assemble()`.

Se https://gist.github.com/KristofferC/4f93bcf8b15fcea4687963e10da0b252

Först skapar man en styvhetsmatris en gång för alltid utanför looparna med `K = create_sparsity_pattern(mesh, dofs)` (du får ändra lite för att få det att funka med edofs men det klarar du nog ;) )

sen assemblerar man med `assemble!(K::SparseMatrixCSC, Ke::Matrix, dofs::Vector{Int})`

Detta kommer bara ha betydelse om resten av din kod är snabb ;)

**Comment by fredrikekre** [comment]
Najs, bara komma ihåg att reseta den innan man assemblerar in i nästa iteration :)

**Comment by KristofferC** [comment]
Ah, precis. `fill!(K.nzval, 0.0)`, inte `fill!(K, 0.0)` för då pajjar du strukturen.

**Comment by KristofferC** [comment]
Alltid bra att benchmarka själv så jag inte fuckat upp min mätning ;)

**Comment by fredrikekre** [comment]
Man kan väl assembla med `begin_assemble()` för att få strukturen?

**Comment by KristofferC** [comment]
`begin_assembly` börjar ju om från scratch? det man vill undvika

**Comment by fredrikekre** [comment]
ja men om man gör det en gång bara, istället för `create_sparsity_pattern(mesh, dofs)`

**Comment by fredrikekre** [comment]
Eller skit samma. Jag tänkte de kunde va enklare om man inte har `mesh` och `dofs` att stoppa in i `create_sparsity_pattern(mesh, dofs)`.

**Comment by KristofferC** [comment]
Du kan ju använda `start_assemble()` och assemblera in en `Ke = ones(dofs, dofs)` typ, sen köra `fill!`.

**Comment by fredrikekre** [comment]
Så jag tänkte :)

**Comment by bajenzulu123** [comment]
Jag A
